services:
    smartcode.generator.payload_smartcode:
        class: Intracto\SmartCodeBundle\Generator\SmartCodeGenerator
        arguments: ['@doctrine.orm.entity_manager']
    smartcode.action.smartcode:
        class: Intracto\SmartCodeBundle\Action\SmartCodeAction
        arguments: ['@doctrine.orm.entity_manager']
